# Generated by Django 4.2.7 on 2023-11-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqt', models.CharField(max_length=30, verbose_name='dars vaqti')),
            ],
        ),
    ]
