# Generated by Django 4.2.7 on 2023-11-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='xona')),
            ],
        ),
        migrations.CreateModel(
            name='Pupils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Familiya')),
                ('phone_number_1', models.CharField(max_length=13, verbose_name='1-telefon raqam')),
                ('phone_number_2', models.CharField(blank=True, max_length=13, null=True, verbose_name='2-telefon raqam')),
                ('lesson_day', models.CharField(blank=True, choices=[('Dushanba', 'DU-CHOR-JUMA'), ('Seshanba', 'SE-PAY-SHANBA')], default='Dushanba', max_length=30, null=True, verbose_name='Kun')),
                ('lesson_time', models.CharField(blank=True, max_length=300, null=True, verbose_name='Sizga qulay dars vaqti')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kim tavsiya berdi')),
                ('is_active_pupil', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='register_pupils', to='lesson.lesson', verbose_name="Yo'nalish")),
            ],
        ),
    ]
