# Generated by Django 4.2.7 on 2023-11-21 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('lesson', '0002_lessontime'),
        ('pupil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='guruh nomi')),
                ('day', models.CharField(choices=[('dushanba', 'DUSHANBA'), ('seshanba', 'SESHANBA')], max_length=30)),
                ('pupils', models.ManyToManyField(to='user.pupil')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='pupil.room', verbose_name='dars xonasi')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson', verbose_name="Yo'nalish")),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.teacher', verbose_name='Ustoz')),
                ('vaqt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.lessontime', verbose_name='dars vaqti')),
            ],
        ),
    ]
